//
// Created by User on 5/22/2022.
//

#ifndef DSA_PW5_SORTEDINDEXEDLIST_BTS_ON_ARRAY_EXTENDEDTEST_H
#define DSA_PW5_SORTEDINDEXEDLIST_BTS_ON_ARRAY_EXTENDEDTEST_H
#pragma once

void testAllExtended();

#endif //DSA_PW5_SORTEDINDEXEDLIST_BTS_ON_ARRAY_EXTENDEDTEST_H
